[tool.poetry]
name = "cbrkit"
version = "1.0.0dev1"
description = "Library for Case-Based Reasoning in Python"
authors = ["Mirko Lenz <mirko@mirkolenz.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/recap-utr/cbrkit"

[tool.poetry.dependencies]
python = ">=3.11, <3.13"
pandas = { version = "^2.1", optional = true }
pyyaml = { version = "^6.0", optional = true }
typer = { version = "^0.9", optional = true }
fastapi = { version = "^0.104", optional = true }

[tool.poetry.group.dev.dependencies]
pytest = "^7.4"

[tool.poetry.extras]
all = ["pandas", "pyyaml", "typer", "fastapi"]
csv = ["pandas"]
pandas = ["pandas"]
yaml = ["pyyaml"]
cli = ["typer"]
rest = ["fastapi"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
