[tool.poetry]
name = "cbrkit"
version = "1.0.0dev1"
description = "Library for Case-Based Reasoning in Python"
authors = ["Mirko Lenz <mirko@mirkolenz.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/wi2trier/cbrkit"
packages = [{ include = "cbrkit" }]

[tool.poetry.scripts]
cbrkit = "cbrkit.cli:app"

[tool.poetry.dependencies]
python = ">=3.11, <3.13"
pandas = "^2.1"
pyyaml = "^6.0"
orjson = "^3.9"
networkx = "^3.2"
pyarrow = "^14.0"
typer = { version = "^0.9", extras = ["all"], optional = true }
fastapi = { version = "^0.104", optional = true, extras = ["all"] }
uvicorn = { version = "^0.24.0.post1", optional = true, extras = ["standard"] }
spacy = { version = "^3.7.2", optional = true }
nltk = { version = "^3.8.1", optional = true }
levenshtein = { version = "^0.23.0", optional = true }

[tool.poetry.group.dev.dependencies]
pytest = "^7.4"
pytest-cov = "^4.1"

[tool.poetry.group.docs.dependencies]
pdoc = "^14.1"

[tool.poetry.extras]
all = ["typer", "fastapi", "spacy", "nltk", "levenshtein"]
cli = ["typer"]
api = ["fastapi", "uvicorn"]
nlp = ["spacy", "nltk", "levenshtein"]

[tool.pytest.ini_options]
addopts = "--cov cbrkit --cov-report term-missing --doctest-modules"
doctest_optionflags = "NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL ELLIPSIS"

[tool.ruff]
target-version = "py311"

[tool.ruff.pydocstyle]
convention = "google"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
